name: "28585 - CI Testiranje"

on:
  push:
    branches:
      - main

jobs:
  preveriCeTestObstaja:
    runs-on: ubuntu-latest
    outputs:
      tests_exist: ${{ steps.check_tests.outputs.tests_exist }}
    steps:
      - name: Nalozi al pa osvezi repozitorij
        uses: actions/checkout@v3

      - name: Preveri obstoj testnih skript
        id: check_tests
        run: |
          if ls tests/*.py 1> /dev/null 2> napaka.txt; then
            echo "tests_exist=true" >> $GITHUB_OUTPUT
          else
            echo "Ni testov!" >> napaka.txt
            echo "tests_exist=false" >> $GITHUB_OUTPUT
          fi

  izvedi_teste:
    needs: preveriCeTestObstaja
    runs-on: ubuntu-latest
    if: needs.preveriCeTestObstaja.outputs.tests_exist == 'true'

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Nalozi al pa osvezi repozitorij
        uses: actions/checkout@v3

      - name: py verzija
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: kniznice
        run: |
          pip install -r requirements.txt || true

      - name: izvedi teste
        run: |
          pytest tests/ || echo "Vses sspesno" > napaka.txt

